In [3]:
#import dependencies
import numpy as np
import pandas as pd
from pathlib import Path

from sklearn.model_selection import train_test_split

In [2]:
train_df = pd.read_csv(Path('Resources/2019loans.csv'))
test_df = pd.read_csv(Path('Resources/2020Q1loans.csv'))

In [ ]:
# Convert categorical data to numeric and separate target feature for training data

In [16]:
dum_train = pd.get_dummies(train_df)
dum_train.head(50)

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N,debt_settlement_flag_Y
0,57107,57107,13375.0,0.1797,483.34,223000.0,29.99,0.0,0.0,15.0,...,1,1,0,1,1,0,1,0,1,0
1,141451,141451,21000.0,0.1308,478.68,123000.0,11.26,2.0,0.0,16.0,...,1,1,0,1,1,0,1,0,1,0
2,321143,321143,20000.0,0.1240,448.95,197000.0,11.28,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
3,11778,11778,3000.0,0.1240,100.22,45000.0,18.08,0.0,0.0,12.0,...,1,1,0,1,1,0,1,0,1,0
4,169382,169382,30000.0,0.1612,1056.49,133000.0,27.77,0.0,2.0,13.0,...,1,1,0,1,1,0,1,0,1,0
5,31295,31295,6500.0,0.1614,228.98,65000.0,27.49,1.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
6,173238,173238,40000.0,0.1240,897.89,171000.0,20.74,0.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
7,116755,116755,5000.0,0.1719,178.74,55000.0,10.80,1.0,0.0,5.0,...,1,1,0,1,1,0,1,0,1,0
8,170311,170311,6000.0,0.1102,196.49,36000.0,27.28,0.0,0.0,19.0,...,1,1,0,1,1,0,1,0,1,0
9,254794,254794,10625.0,0.1102,347.95,73000.0,7.09,0.0,2.0,18.0,...,1,1,0,1,1,0,1,0,1,0
10,38248,38248,22625.0,0.0702,698.81,75000.0,34.86,0.0,0.0,5.0,...,1,1,0,1,0,1,1,0,1,0
11,32758,32758,8000.0,0.1614,281.81,29000.0,24.63,0.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
12,248585,248585,35000.0,0.0756,1089.69,90000.0,27.75,0.0,0.0,22.0,...,1,1,0,1,1,0,1,0,1,0
13,79308,79308,4800.0,0.0819,150.84,40000.0,23.01,0.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
14,22954,22954,11000.0,0.0881,348.83,85000.0,12.76,0.0,1.0,4.0,...,1,1,0,1,1,0,1,0,1,0
15,163076,163076,28000.0,0.0881,578.66,155000.0,9.45,3.0,0.0,14.0,...,1,1,0,1,1,0,1,0,1,0
16,15902,15902,7500.0,0.1033,243.17,41000.0,27.59,0.0,1.0,13.0,...,1,1,1,0,1,0,1,0,1,0
17,1655,1655,10000.0,0.1557,349.46,98000.0,5.56,0.0,0.0,9.0,...,1,1,1,0,1,0,1,0,1,0
18,38852,38852,12850.0,0.1447,442.13,40000.0,21.00,0.0,0.0,9.0,...,1,1,1,0,1,0,1,0,1,0
19,310148,310148,37000.0,0.1033,792.17,98600.0,29.69,0.0,1.0,13.0,...,1,1,0,1,1,0,1,0,1,0
20,218933,218933,4200.0,0.2055,157.27,50000.0,33.20,0.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
21,188764,188764,2000.0,0.1774,72.05,145000.0,6.81,0.0,0.0,6.0,...,1,1,0,1,1,0,1,0,1,0
22,93933,93933,15000.0,0.0819,471.37,75000.0,26.08,1.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
23,126737,126737,12750.0,0.0881,404.33,120000.0,15.30,0.0,0.0,10.0,...,1,1,0,1,0,1,1,0,1,0
24,9139,9139,15000.0,0.2000,557.46,48000.0,25.58,0.0,2.0,12.0,...,1,1,0,1,1,0,1,0,1,0
25,322203,322203,5300.0,0.1430,181.92,36000.0,32.43,0.0,0.0,13.0,...,1,1,0,1,1,0,1,0,1,0
26,157907,157907,20000.0,0.1308,674.65,50000.0,12.29,0.0,0.0,6.0,...,1,1,0,1,1,0,1,0,1,0
27,11693,11693,15000.0,0.1557,361.36,53000.0,31.48,2.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
28,91856,91856,19000.0,0.0819,386.99,162600.0,7.71,1.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
29,60000,60000,20000.0,0.1072,652.13,170000.0,19.07,0.0,4.0,18.0,...,1,1,1,0,1,0,1,0,1,0
30,172792,172792,22000.0,0.0756,684.95,100000.0,22.80,0.0,0.0,10.0,...,1,1,0,1,0,1,1,0,1,0
31,42789,42789,20000.0,0.1131,657.72,85600.0,25.30,0.0,0.0,17.0,...,1,1,0,1,1,0,1,0,1,0
32,147140,147140,34850.0,0.0819,1095.13,150000.0,15.39,0.0,0.0,6.0,...,1,1,0,1,1,0,1,0,1,0
33,64995,64995,25000.0,0.0819,785.61,55000.0,31.16,0.0,0.0,13.0,...,1,1,0,1,1,0,1,0,1,0
34,261297,261297,10000.0,0.0881,317.12,85000.0,11.28,0.0,0.0,6.0,...,1,1,0,1,1,0,1,0,1,0
35,256776,256776,5000.0,0.1774,180.12,30000.0,35.24,4.0,0.0,8.0,...,1,1,1,0,1,0,1,0,1,0
36,212075,212075,6000.0,0.1695,213.77,120000.0,13.71,1.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
37,292415,292415,11000.0,0.0756,342.48,88000.0,12.41,1.0,0.0,10.0,...,1,1,0,1,1,0,1,0,1,0
38,218902,218902,25000.0,0.1033,810.56,180000.0,25.07,1.0,0.0,11.0,...,1,1,0,1,1,0,1,0,1,0
39,78700,78700,20925.0,0.0819,657.55,98000.0,27.15,1.0,0.0,9.0,...,1,1,0,1,0,1,1,0,1,0
40,340003,340003,11000.0,0.0819,345.67,51996.0,12.14,0.0,0.0,6.0,...,1,1,0,1,1,0,1,0,1,0
41,58378,58378,8000.0,0.1180,264.96,25000.0,31.16,0.0,3.0,11.0,...,1,1,0,1,1,0,1,0,1,0
42,2093,2093,5050.0,0.0881,160.15,75000.0,8.21,0.0,0.0,11.0,...,1,1,0,1,1,0,1,0,1,0
43,338302,338302,1250.0,0.1524,43.48,66000.0,30.16,0.0,1.0,13.0,...,1,1,0,1,1,0,1,0,1,0
44,229473,229473,17000.0,0.2000,631.79,51000.0,32.49,0.0,0.0,9.0,...,1,1,0,1,1,0,1,0,1,0
45,4000,4000,10000.0,0.2000,371.64,28000.0,9.43,0.0,1.0,11.0,...,1,1,0,1,1,0,1,0,1,0
46,303724,303724,30000.0,0.2565,1203.14,85000.0,36.13,0.0,0.0,11.0,...,1,1,1,0,1,0,1,0,1,0
47,148900,148900,30000.0,0.0881,619.99,100000.0,16.42,0.0,1.0,13.0,...,1,1,0,1,1,0,1,0,1,0
48,262446,262446,10000.0,0.2000,371.64,75000.0,11.33,0.0,1.0,10.0,...,1,1,0,1,1,0,1,0,1,0
49,163407,163407,7000.0,0.1430,240.27,50000.0,28.66,1.0,0.0,8.0,...,1,1,0,1,1,0,1,0,1,0

In [7]:
# Convert categorical data to numeric and separate target feature for testing data
dum_test = pd.get_dummies(test_df)
dum_test.head()

,Unnamed: 0,index,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,...,loan_status_high_risk,loan_status_low_risk,pymnt_plan_n,initial_list_status_f,initial_list_status_w,application_type_Individual,application_type_Joint App,hardship_flag_N,hardship_flag_Y,debt_settlement_flag_N
0,67991,67991,40000.0,0.0819,814.70,140000.0,19.75,0.0,1.0,18.0,...,0,1,1,0,1,1,0,1,0,1
1,25429,25429,6000.0,0.1524,208.70,55000.0,11.52,2.0,0.0,8.0,...,0,1,1,0,1,1,0,1,0,1
2,38496,38496,3600.0,0.1695,128.27,42000.0,6.74,0.0,0.0,6.0,...,0,1,1,0,1,1,0,1,0,1
3,19667,19667,20000.0,0.1524,478.33,100000.0,12.13,0.0,2.0,7.0,...,0,1,1,0,1,1,0,1,0,1
4,37505,37505,3600.0,0.1240,120.27,50000.0,16.08,0.0,3.0,6.0,...,0,1,1,0,1,1,0,1,0,1

In [9]:
#view the columns in the training data
dum_train.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'loan_status_high_risk', 'loan_status_low_risk', 'pymnt_plan_n',
       'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N',
       'debt_settlement_flag_Y'],
      dtype='object')

In [14]:
dum_test.columns

Index(['Unnamed: 0', 'index', 'loan_amnt', 'int_rate', 'installment',
       'annual_inc', 'dti', 'delinq_2yrs', 'inq_last_6mths', 'open_acc',
       'pub_rec', 'revol_bal', 'total_acc', 'out_prncp', 'out_prncp_inv',
       'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_amnt', 'collections_12_mths_ex_med', 'policy_code',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_act_il', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_within_12_mths', 'delinq_amnt', 'mo_sin_old_il_acct',
       'mo_sin_old_rev_tl_op', 'mo_sin_rcnt_rev_tl_op', 'mo_sin_rcnt_tl',
       'mort_acc', 'mths_since_recent_bc', 'mths_since_recent_inq',
       'num_accts_ever_120_pd', 'num_actv_bc_tl', 'num_actv_rev_tl',
       'num_bc_sats', 'num_bc_tl', 'num_il_tl', 'num_op_rev_tl',
       'num_rev_accts', 'num_rev_tl_bal_gt_0', 'num_sats', 'num_tl_120dpd_2m',
       'num_tl_30dpd', 'num_tl_90g_dpd_24m', 'num_tl_op_past_12m',
       'pct_tl_nvr_dlq', 'percent_bc_gt_75', 'pub_rec_bankruptcies',
       'tax_liens', 'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit', 'home_ownership_ANY',
       'home_ownership_MORTGAGE', 'home_ownership_OWN', 'home_ownership_RENT',
       'verification_status_Not Verified',
       'verification_status_Source Verified', 'verification_status_Verified',
       'loan_status_high_risk', 'loan_status_low_risk', 'pymnt_plan_n',
       'initial_list_status_f', 'initial_list_status_w',
       'application_type_Individual', 'application_type_Joint App',
       'hardship_flag_N', 'hardship_flag_Y', 'debt_settlement_flag_N'],
      dtype='object')

In [17]:
print(len(dum_train.columns))
print(len(dum_test.columns))

96
95

In [ ]:
# add missing dummy variables to testing set

In [ ]:
# Train the Logistic Regression model on the unscaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model and print the model score

In [ ]:
# Scale the data

In [ ]:
# Train the Logistic Regression model on the scaled data and print the model score

In [ ]:
# Train a Random Forest Classifier model on the scaled data and print the model score